---
- hosts: local
  vars_files:
    - defaults/main.yml
  roles:
    - role1
    - role2
    - cloudalchemy.grafana

  tasks:
    - name: "Debug"
      debug:
        msg: "Working Fine... {{ grafana_security.admin_password }}"